---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: boclipsconcourse/junit2alertmanager
    tag: "0.2.0"

inputs:
- name: test-results

params:
  ALERT_MANAGER_HOSTS:

run:
  path: /bin/sh
  args:
  - -c
  - |
    /go/bin/junit2alertmanager \
      --junit test-results/test-output.xml \
      --alert-name "Smoke Tests" \
      --labels severity=warning
