---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cypress/browsers
    tag: "node12.14.1-chrome83-ff77"

inputs:
- name: source

outputs:
- name: test-results

run:
  path: sh
  args:
  - -ec
  - |-
    cd source/ui
    npm ci
    npm run test -- --spec="$SPEC" --browser chrome

params:
  CYPRESS_PUBLISHER_USERNAME:
  CYPRESS_PUBLISHER_PASSWORD:
  SPEC:

caches:
- path: ../../../root/.cache
- path: ../../../root/.npm
