---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cypress/browsers
    tag: "node12.14.1-chrome83-ff77"

inputs:
- name: source

outputs:
- name: test-results
- name: metrics

run:
  path: source/pipeline/scripts/cypress

params:
  SPEC:

caches:
- path: ../../../root/.cache
- path: ../../../root/.npm
