---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cypress/base
    tag: "10"

inputs:
- name: source

outputs:
- name: test-results
- name: metrics

run:
  path: source/pipeline/scripts/cypress

params:
  CYPRESS_PUBLISHER_USERNAME:
  CYPRESS_PUBLISHER_PASSWORD:

caches:
- path: ../../../root/.cache
- path: ../../../root/.npm
