---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cypress/base
    tag: "10"

inputs:
- name: source

outputs:
- name: test-results

run:
  path: source/pipeline/scripts/run

caches:
- path: ../../../root/.cache
- path: ../../../root/.npm
