---
jobs:
- name: run
  plan:
  - get: source
    resource: smoke-tests
  - task: run
    file: smoke-tests/pipeline/tasks/run.yml
    on_failure:
      in_parallel:
      - task: alert
        file: smoke-tests/pipeline/tasks/alert.yml
        params:
          ALERT_MANAGER_HOSTS: ((alert-manager.hosts))
      - put: test-results
        params:
          file: test-results/results.tar
          predefined_acl: projectPrivate

resources:
- name: smoke-tests
  type: git
  source:
    branch: master
    uri: https://github.com/boclips/smoke-tests.git

- name: test-results
  type: gcs
  source:
    bucket: boclips-test-results
    json_key: ((gcs.key))
    versioned_file: "smoke-tests/results.tar"

- name: gcs
  type: registry-image
  source:
    repository: frodenas/gcs-resource
    tag: "v0.5.1"
