---
meta:
  upload_media:
    &upload_media
    put: test-results
    params:
      file: test-results/results.tar
      predefined_acl: projectPrivate

  upload_metrics:
    &upload_metrics
    put: replace-me
    params:
      file: metrics/prometheus
      cache_control: "private, max-age=0, no-transform"
      predefined_acl: "publicRead"

jobs:
- name: publishers
  plan:
  - get: source
    resource: smoke-tests
  - get: not-often
    trigger: true
  - task: run
    file: source/pipeline/tasks/cypress.yaml
    params:
      SPEC: cypress/integration/publishers.spec.ts
    on_failure: *upload_media
    ensure:
      <<: *upload_metrics
      put: publishers-metrics

- name: getty-ingest
  plan:
  - get: source
    resource: smoke-tests
  - get: not-often
    trigger: true
  - task: run
    file: source/pipeline/tasks/cypress.yaml
    params:
      SPEC: cypress/integration/getty-ingest.spec.ts
    on_failure: *upload_media
    ensure:
      <<: *upload_metrics
      put: getty-ingest-metrics

- name: p1s
  plan:
  - get: source
    resource: smoke-tests
  - get: not-often
    trigger: true
  - task: run
    file: source/pipeline/tasks/jest.yaml
    params:
      SPEC: ./api/*
    ensure:
      <<: *upload_metrics
      put: p1-metrics

resources:
- name: smoke-tests
  type: git
  icon: fire
  source:
    branch: master
    uri: https://github.com/boclips/smoke-tests.git

- name: test-results
  type: gcs
  icon: video
  source:
    bucket: boclips-test-results
    json_key: ((gcs.key))
    versioned_file: "smoke-tests/results.tar"

- name: publishers-metrics
  type: gcs
  icon: chart-line
  source:
    bucket: boclips-smoke-test-metrics
    json_key: ((gcs.key))
    versioned_file: publishers

- name: getty-ingest-metrics
  type: gcs
  icon: chart-line
  source:
    bucket: boclips-smoke-test-metrics
    json_key: ((gcs.key))
    versioned_file: getty-ingest

- name: p1-metrics
  type: gcs
  icon: chart-line
  source:
    bucket: boclips-smoke-test-metrics
    json_key: ((gcs.key))
    versioned_file: p1-metrics

- name: not-often
  type: time
  icon: clock-outline
  source:
    interval: 10m

resource_types:
- name: gcs
  type: registry-image
  source:
    repository: frodenas/gcs-resource
    tag: "v0.5.1"
